'use client';
import {useEffect,useRef,useState} from 'react';
import {Pickaxe,MapPin,Layers,Route,BookOpen,Search,X,ArrowLeft,ExternalLink,Mountain,Car,Droplets,Landmark,ChevronRight,Info,Download,RefreshCw} from 'lucide-react';
import type * as GeoJSON from 'geojson';
import type {Map as GLMap} from 'maplibre-gl';
import {PIACENZA_BOUNDS,regionalLayers,localCategories,regionalReferences,wmsTile,validRegionalPoint} from '@/lib/piacenza';
import manifest from '@/data/piacenza-manifest.json';
type Feature=GeoJSON.Feature<GeoJSON.Geometry,Record<string,any>>;
const empty:GeoJSON.FeatureCollection={type:'FeatureCollection',features:[]};
const initialCategories=['mine','geosite'];
const defaultLayers=regionalLayers.filter(l=>l.defaultOn).map(l=>l.id);
const colors:Record<string,string>={mine:'#a34425',geosite:'#187970',resource:'#996817',outcrop:'#8f6638',parking:'#3266a4',spring:'#207caf',viewpoint:'#7652a0',museum:'#8a5077',heritage:'#747047',shelter:'#6f6346',visitor:'#53654b'};
function clean(v:unknown){return v!==null&&v!==undefined&&!['','null','none','nd'].includes(String(v).trim().toLowerCase());}
function safeLink(v:unknown){return typeof v==='string'&&/^https?:\/\//i.test(v)?v:undefined;}
function original(f:Feature){try{return JSON.parse(f.properties?.raw||'{}')}catch{return {}}}
function coordinates(g:GeoJSON.Geometry):number[][]{if(g.type==='GeometryCollection')return g.geometries.flatMap(coordinates);const collect=(a:any):number[][]=>typeof a[0]==='number'?[a]:a.flatMap(collect);return collect(g.coordinates);}
function Symbol({kind,size=20}:{kind:string;size?:number}){const I=kind==='mine'?Pickaxe:kind==='parking'?Car:kind==='spring'?Droplets:kind==='museum'?Landmark:kind==='trail'||kind==='geotrail'?Route:Mountain;return <I size={size}/>}
export default function PiacenzaExplorer({map,open,onOpen,onClose,lang}:{map:GLMap|null;open:boolean;onOpen:()=>void;onClose:()=>void;lang:string}){
 const it=lang==='it',say=(en:string,italian:string)=>it?italian:en;
 const [section,setSection]=useState('sites'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Feature|null>(null);
 const [points,setPoints]=useState<Feature[]>([]),[paths,setPaths]=useState<Feature[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[ready,setReady]=useState(false),[revision,setRevision]=useState(0);
 const [categories,setCategories]=useState(initialCategories),[overlays,setOverlays]=useState(defaultLayers),[trails,setTrails]=useState(false),[areas,setAreas]=useState(false),[opacity,setOpacity]=useState(55);
 const [inspection,setInspection]=useState<{point:{lat:number;lng:number};rows:any[];loading:boolean}|null>(null);
 const featuresRef=useRef<Feature[]>([]),openRef=useRef(onOpen),overlaysRef=useRef(overlays),token=useRef(0),view=useRef({west:9.15,south:44.45,east:10.15,north:45.2});
 openRef.current=onOpen;overlaysRef.current=overlays;
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem('strata-piacenza-v1')||'null');if(v){if(Array.isArray(v.categories))setCategories(v.categories.filter((x:string)=>localCategories.some(c=>c[0]===x)));if(Array.isArray(v.overlays))setOverlays(v.overlays.filter((x:string)=>regionalLayers.some(l=>l.id===x)));setTrails(!!v.trails);setAreas(!!v.areas);if(Number.isFinite(v.opacity))setOpacity(Math.min(100,Math.max(10,v.opacity)));}}catch{}},[]);
 useEffect(()=>{localStorage.setItem('strata-piacenza-v1',JSON.stringify({categories,overlays,trails,areas,opacity}));},[categories,overlays,trails,areas,opacity]);
 async function loadPoints(){setBusy(true);setError('');try{const r=await fetch('/data/piacenza/points.geojson');if(!r.ok)throw new Error('Regional records could not load.');const d:any=await r.json();setPoints(d.features);featuresRef.current=[...d.features,...paths];}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{loadPoints()},[]);
 useEffect(()=>{if(!trails||paths.length)return;let cancelled=false;fetch('/data/piacenza/trails.geojson').then(r=>{if(!r.ok)throw new Error('Regional trails could not load.');return r.json()}).then((d:any)=>{if(!cancelled){setPaths(d.features);featuresRef.current=[...points,...d.features]}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[trails,paths.length,points]);
 async function inspectPoint(lat:number,lng:number){if(!validRegionalPoint(lat,lng))return;const seq=++token.current;setSelected(null);setInspection({point:{lat,lng},rows:[],loading:true});openRef.current();const enabled=regionalLayers.filter(l=>overlaysRef.current.includes(l.id)&&l.queryable);const rows=await Promise.all(enabled.map(async l=>{try{const r=await fetch(`/api/piacenza?layer=${l.id}&lat=${lat}&lng=${lng}`);const d:any=await r.json();return {...d,id:l.id,name:l.name}}catch{return {id:l.id,name:l.name,error:'Source unavailable'}}}));if(seq===token.current)setInspection({point:{lat,lng},rows,loading:false});}
 function select(f:Feature,fly=false){++token.current;setSelected(f);setInspection(null);openRef.current();if(fly&&map){const cs=coordinates(f.geometry);if(f.geometry.type==='Point')map.easeTo({center:cs[0] as [number,number],zoom:Math.max(map.getZoom(),12),offset:map.getContainer().clientWidth<700?[0,-map.getContainer().clientHeight*.22]:[170,0]});else map.fitBounds([[Math.min(...cs.map(c=>c[0])),Math.min(...cs.map(c=>c[1]))],[Math.max(...cs.map(c=>c[0])),Math.max(...cs.map(c=>c[1]))]],{padding:80,maxZoom:14});}}
 useEffect(()=>{if(!map)return;let cancelled=false;const m=map;
 for(const l of regionalLayers){m.addSource(l.id,{type:'raster',tiles:[wmsTile(l)],tileSize:256,bounds:PIACENZA_BOUNDS,attribution:'© <a href="https://geoportale.regione.emilia-romagna.it">Regione Emilia-Romagna</a> · CC BY 4.0'});m.addLayer({id:l.id,type:'raster',source:l.id,layout:{visibility:'none'},paint:{'raster-opacity':.55}},'clusters');}
 m.addSource('pc-areas',{type:'geojson',data:empty});m.addLayer({id:'pc-area-fill',type:'fill',source:'pc-areas',paint:{'fill-color':'#1b887d','fill-opacity':.12}});m.addLayer({id:'pc-area-line',type:'line',source:'pc-areas',paint:{'line-color':'#1b887d','line-width':2}});
 m.addSource('pc-paths',{type:'geojson',data:empty,attribution:'REER / Regione Emilia-Romagna · CC BY 4.0'});m.addLayer({id:'pc-trails',type:'line',source:'pc-paths',paint:{'line-color':['match',['get','kind'],'geotrail','#8b5294','#be3953'],'line-width':2,'line-opacity':.8}});
 m.addSource('pc-points',{type:'geojson',data:empty,attribution:'ISPRA / APAT · Regione Emilia-Romagna · CC BY 4.0'});
 m.addLayer({id:'pc-pois',type:'circle',source:'pc-points',filter:['!=',['get','kind'],'mine'],paint:{'circle-radius':['interpolate',['linear'],['zoom'],8,4,13,7],'circle-color':['match',['get','kind'],...Object.entries(colors).flat(),'#187970'] as any,'circle-stroke-color':'#fff','circle-stroke-width':2}});
 // A pickaxe symbol distinguishes documented mining records from other POIs.
 const icon=new Image(36,36);icon.onload=()=>{if(cancelled)return;m.addImage('pc-pickaxe',icon,{pixelRatio:1.5});m.addLayer({id:'pc-mines',type:'symbol',source:'pc-points',filter:['==',['get','kind'],'mine'],layout:{'icon-image':'pc-pickaxe','icon-size':1,'icon-allow-overlap':true,'icon-ignore-placement':true}});setReady(true)};icon.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 36 36"><circle cx="18" cy="18" r="16" fill="#a34425" stroke="white" stroke-width="3"/><g transform="translate(7,7)" fill="none" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m14 10-8.5 8.5a2.1 2.1 0 0 1-3-3L11 7"/><path d="M16 3a8 8 0 0 1 5 5l-4 1-7-7 1-1 5 2Z"/><path d="m9 3 10 10"/></g></svg>');
 const click=(e:any)=>{if(e.originalEvent?.defaultPrevented)return;const layerIds=['pc-mines','pc-pois','pc-trails'].filter(id=>m.getLayer(id));const hit=m.queryRenderedFeatures([[e.point.x-5,e.point.y-5],[e.point.x+5,e.point.y+5]],{layers:layerIds})[0];if(hit){const f=featuresRef.current.find(f=>f.properties.id===hit.properties.id);if(f){select(f);return;}}const c=e.lngLat;if(validRegionalPoint(c.lat,c.lng))inspectPoint(c.lat,c.lng);};
 const move=()=>{const b=m.getBounds();view.current={west:b.getWest(),south:b.getSouth(),east:b.getEast(),north:b.getNorth()};setRevision(v=>v+1)};
 m.on('click',click);m.on('moveend',move);move();return()=>{cancelled=true;m.off('click',click);m.off('moveend',move);};
 },[map]);
 useEffect(()=>{if(!map||!ready)return;const fs=points.filter(f=>categories.includes(f.properties.kind)&&(!query||[f.properties.name,f.properties.minerals,f.properties.municipality,f.properties.description].join(' ').toLowerCase().includes(query.toLowerCase())));(map.getSource('pc-points') as any)?.setData({type:'FeatureCollection',features:fs});for(const l of regionalLayers){map.setLayoutProperty(l.id,'visibility',overlays.includes(l.id)?'visible':'none');map.setPaintProperty(l.id,'raster-opacity',opacity/100);}},[points,categories,query,overlays,opacity,map,ready]);
 useEffect(()=>{if(!map||!ready)return;(map.getSource('pc-paths') as any)?.setData(trails?{type:'FeatureCollection',features:paths}:empty);},[map,ready,trails,paths]);
 useEffect(()=>{if(!map||!ready)return;let cancelled=false;if(!areas){(map.getSource('pc-areas') as any)?.setData(empty);return}fetch('/data/piacenza/areas.geojson').then(r=>{if(!r.ok)throw new Error('Geosite boundaries could not load');return r.json()}).then((d:any)=>{if(!cancelled)(map.getSource('pc-areas') as any)?.setData(d)}).catch(e=>setError(e.message));return()=>{cancelled=true}},[map,ready,areas]);
 const filtered=points.filter(f=>categories.includes(f.properties.kind)&&(!query||[f.properties.name,f.properties.minerals,f.properties.municipality,f.properties.description].join(' ').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>Number(b.properties.kind==='mine')-Number(a.properties.kind==='mine')||a.properties.name.localeCompare(b.properties.name));
 const visible=filtered.filter(f=>{const [x,y]=(f.geometry as GeoJSON.Point).coordinates,b=view.current;return x>=b.west&&x<=b.east&&y>=b.south&&y<=b.north});
 const toggle=(v:string,list:string[],set:(v:string[])=>void)=>set(list.includes(v)?list.filter(x=>x!==v):[...list,v]);
 const bounds=()=>map?.fitBounds([[PIACENZA_BOUNDS[0],PIACENZA_BOUNDS[1]],[PIACENZA_BOUNDS[2],PIACENZA_BOUNDS[3]]],{padding:45});
 if(!open)return null;
 return <aside className="explore-panel pc-panel" aria-label={say('Piacenza exploration','Esplorazione Piacenza')}>
 <div className="panel-intro"><div><span className="eyebrow">{say('REGIONAL FIELD ATLAS','ATLANTE GEOLOGICO LOCALE')}</span><h1>Piacenza</h1><p className="pc-subtitle">{say('Mines, rocks & places to explore','Miniere, rocce e luoghi da esplorare')}</p></div><button className="icon-button" aria-label={say('Close Piacenza','Chiudi Piacenza')} onClick={onClose}><X size={20}/></button></div>
 <div className="pc-nav"><button onClick={()=>{setSelected(null);setInspection(null);setSection('sites')}} className={section==='sites'?'active':''}><Pickaxe size={16}/>{say('Sites','Siti')}</button><button onClick={()=>{setSelected(null);setInspection(null);setSection('layers')}} className={section==='layers'?'active':''}><Layers size={16}/>{say('Layers','Livelli')}</button><button onClick={()=>{setSelected(null);setInspection(null);setSection('guides')}} className={section==='guides'?'active':''}><BookOpen size={16}/>{say('Guides','Guide')}</button></div>
 <div className="panel-scroll">
 {error&&<div role="status" className="notice">{error}<button onClick={loadPoints}><RefreshCw size={16}/>{say('Retry','Riprova')}</button></div>}
 {selected?<><button className="text-link" onClick={()=>setSelected(null)}><ArrowLeft size={16}/>{say('All sites','Tutti i siti')}</button><div className={`pc-detail-symbol kind-${selected.properties.kind}`}><Symbol kind={selected.properties.kind} size={26}/></div><span className="eyebrow">{selected.properties.kind==='mine'?say('HISTORICAL MINING RECORD','DOCUMENTO MINERARIO STORICO'):say('REGIONAL SOURCE RECORD','DOCUMENTO REGIONALE')}</span><h2>{selected.properties.name}</h2><p>{selected.properties.description}</p>
 <dl className="facts">{[[say('Municipality','Comune'),selected.properties.municipality],[say('Reported minerals / material','Minerali / materiale riportati'),selected.properties.minerals],[say('Activity period','Periodo di attività'),selected.properties.period],[say('Status in historical source','Stato nella fonte storica'),selected.properties.historicalStatus],[say('Source date / edition','Data / edizione della fonte'),selected.properties.updated]].filter(([,v])=>clean(v)).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
 {selected.properties.kind==='mine'&&<div className="notice warning"><Pickaxe size={20}/><p>{say('Historical evidence, not a verified entrance or a current operating mine. Access, ownership and collecting permission are unknown.','Testimonianza storica, non un ingresso verificato né una miniera oggi attiva. Accesso, proprietà e permesso di raccolta non sono noti.')}</p></div>}
 <p className="metadata">{selected.properties.positionNote}</p>
 <div className="action-row"><button className="secondary" onClick={()=>select(selected,true)}><MapPin size={16}/>{say('Focus on map','Centra sulla mappa')}</button>{safeLink(selected.properties.gpx)&&<a className="secondary" href={selected.properties.gpx} target="_blank" rel="noreferrer"><Download size={16}/>GPX</a>}</div>
 <h3>{say('Original source information','Informazioni originali')}</h3><p className="metadata">{selected.properties.source} · {selected.properties.licence}<br/>{say('Retrieved','Consultato')} {new Date(selected.properties.retrievedAt).toLocaleDateString()}</p>
 <a className="text-link" href={safeLink(selected.properties.recordUrl)} target="_blank" rel="noreferrer">{say('Open original record','Apri la scheda originale')}<ExternalLink size={14}/></a>
 <details className="pc-raw"><summary>{say('All original attributes','Tutti gli attributi originali')}</summary><dl className="facts">{Object.entries(original(selected)).filter(([,v])=>clean(v)).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{safeLink(v)?<a href={String(v)} target="_blank" rel="noreferrer">{say('Source link','Link alla fonte')}</a>:String(v)}</dd></div>)}</dl></details>
 <h3>{say('Other records nearby','Altri documenti vicini')}</h3>{points.filter(f=>f.properties.id!==selected.properties.id&&f.properties.kind==='mine'&&selected.geometry.type==='Point'&&Math.hypot(...(f.geometry as GeoJSON.Point).coordinates.map((v,i)=>v-(selected.geometry as GeoJSON.Point).coordinates[i]) as [number,number])<.015).map(f=><button className="region-row" key={f.properties.id} onClick={()=>select(f)}><Pickaxe size={18}/><span>{f.properties.name}<small>{f.properties.source}</small></span></button>)}<p className="metadata">{say('Separate source records are retained. Nearby records may describe the same workings; proximity alone does not establish a match.','Le fonti restano separate. Documenti vicini possono riferirsi agli stessi lavori; la vicinanza non prova la corrispondenza.')}</p>
 </>:inspection?<><button className="text-link" onClick={()=>setInspection(null)}><ArrowLeft size={16}/>{say('All sites','Tutti i siti')}</button><h2>{say('Regional map inspection','Lettura della carta regionale')}</h2><p className="metadata">{inspection.point.lat.toFixed(5)}, {inspection.point.lng.toFixed(5)}</p>{inspection.loading?<p role="status">{say('Reading enabled regional layers…','Interrogazione dei livelli regionali attivi…')}</p>:inspection.rows.length?inspection.rows.map(row=><div className="geology-unit" key={row.id}><h3>{row.name}</h3>{row.error?<p>{row.error}</p>:<>{row.features?.length?row.features.map((f:any,i:number)=><dl className="facts" key={i}>{Object.entries(f.properties||{}).filter(([k,v])=>!k.toLowerCase().includes('shape')&&clean(v)).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{safeLink(v)?<a href={String(v)} target="_blank" rel="noreferrer">{say('Source link','Link alla fonte')}</a>:String(v)}</dd></div>)}</dl>):<p className="metadata">{say('No source feature returned at this point.','Nessun elemento restituito in questo punto.')}</p>}<a href={row.url} target="_blank" rel="noreferrer" className="text-link">{say('Original query','Interrogazione originale')}<ExternalLink size={13}/></a></>}</div>):<p>{say('Enable a queryable regional layer to inspect this point.','Attiva un livello regionale interrogabile.')}</p>}</>:section==='sites'?<>
 <div className="pc-overview"><Pickaxe size={24}/><div><strong>{manifest.counts.mine} {say('mining records','documenti minerari')}</strong><small>{say('ISPRA census + regional geosites','Censimento ISPRA + geositi regionali')}</small></div></div>
 <label className="pc-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={say('Mine, mineral, municipality…','Miniera, minerale, comune…')} aria-label={say('Search Piacenza sites','Cerca siti di Piacenza')}/></label>
 <div className="pc-categories">{localCategories.map(([k,en,italian])=><button aria-pressed={categories.includes(k)} key={k} className={categories.includes(k)?'active':''} onClick={()=>toggle(k,categories,setCategories)}>{it?italian:en}<span>{(manifest.counts as Record<string,number>)[k]||0}</span></button>)}</div>
 <div className="section-heading"><span>{visible.length} {say('in this map view','in questa vista')}</span><button className="text-link" onClick={bounds}>{say('Show region','Mostra regione')}</button></div>
 {busy?<p role="status">{say('Loading official records…','Caricamento dei dati ufficiali…')}</p>:visible.length?<div className="report-list">{visible.slice(0,100).map(f=><button className="report-card" key={f.properties.id} onClick={()=>select(f,true)}><span className={`pc-symbol kind-${f.properties.kind}`}><Symbol kind={f.properties.kind}/></span><span className="report-text"><strong>{f.properties.name}</strong><span>{f.properties.minerals||f.properties.municipality||f.properties.sourceLayer.replaceAll('_',' ')}</span><small>{f.properties.source}</small></span><ChevronRight size={16}/></button>)}</div>:<div className="empty-state"><MapPin size={28}/><p>{say('No matching records in this view. Change the filters or return to Piacenza.','Nessun risultato in questa vista. Cambia i filtri o torna a Piacenza.')}</p><button className="secondary" onClick={bounds}>{say('Show Piacenza','Mostra Piacenza')}</button></div>}
 {visible.length>100&&<p className="metadata">{say('First 100 listed; all matching categories remain on the map.','Primi 100 elencati; tutte le categorie selezionate restano sulla mappa.')}</p>}
 </>:section==='layers'?<><p className="subtle">{say('Click a mine symbol for its record, a trail for its details, or the map to inspect enabled regional layers.','Clicca una miniera per la scheda, un sentiero per i dettagli, o la mappa per interrogare i livelli attivi.')}</p>
 {regionalLayers.map(l=><div key={l.id}><label className="layer-row"><span>{it?l.it:l.name}<small>{l.note}</small></span><input type="checkbox" checked={overlays.includes(l.id)} onChange={()=>toggle(l.id,overlays,setOverlays)}/></label></div>)}
 <label className="opacity-label">{say('Regional overlay opacity','Opacità dei livelli regionali')}<span>{opacity}%</span><input aria-label={say('Regional overlay opacity','Opacità dei livelli regionali')} type="range" min="10" max="100" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label>
 <label className="layer-row"><span>{say('Geosite boundaries','Perimetri dei geositi')}<small>38 · Regione Emilia-Romagna</small></span><input type="checkbox" checked={areas} onChange={e=>setAreas(e.target.checked)}/></label>
 <label className="layer-row"><span>{say('Hiking & geological itineraries','Sentieri e itinerari geoambientali')}<small>REER + itinerari geoambientali · {manifest.counts.trail+manifest.counts.geotrail} {say('source features','elementi')}</small></span><input type="checkbox" checked={trails} onChange={e=>setTrails(e.target.checked)}/></label>
 <p className="metadata">{say('Recorded trails, not calculated routes. Select a trail to see its source date, difficulty, length and GPX when supplied.','Sentieri censiti, non percorsi calcolati. Seleziona un sentiero per data, difficoltà, lunghezza e GPX quando disponibili.')}</p>
 <details><summary>{say('Map legends from the provider','Legende cartografiche originali')}</summary>{regionalLayers.filter(l=>overlays.includes(l.id)).map(l=><a className="region-row" key={l.id} href={`https://servizigis.regione.emilia-romagna.it/wms/${l.service}?service=WMS&version=1.1.1&request=GetLegendGraphic&format=image/png&layer=${l.layers.split(',')[0]}`} target="_blank" rel="noreferrer">{it?l.it:l.name}<ExternalLink size={14}/></a>)}</details>
 </>:<><h2>{say('Field guides & planning maps','Guide e carte di pianificazione')}</h2>{regionalReferences.map(r=><a className="pc-reference" key={r.url} href={r.url} target="_blank" rel="noreferrer"><strong>{it?r.it:r.name}<ExternalLink size={16}/></strong><p>{r.note}</p></a>)}<div className="notice"><Info size={19}/><p>{say('PIAE plans and park guides are linked to the official publications. Their geometries have not been invented or traced without a verified source.','I piani PIAE e le guide del parco rimandano alle pubblicazioni ufficiali. Non sono state inventate geometrie.')}</p></div><h3>{say('Download the source snapshots','Scarica i dati delle fonti')}</h3>{['points','trails','areas'].map(k=><a key={k} className="region-row" href={`/data/piacenza/${k}.geojson`} download><Download size={17}/>{k} · GeoJSON</a>)}</>}
 </div><footer className="pc-footer"><span className="pc-mini-pick"><Pickaxe size={15}/></span><span>{say('Piacenza + surroundings · source records','Piacenza e dintorni · documenti delle fonti')}<small>{say('Mines/geosites: province. Other features: regional bounding box.','Miniere/geositi: provincia. Altri elementi: area circostante.')}</small></span></footer></aside>
}
