import type {Source} from './registry';
import {regionalLayers} from './piacenza';
import manifest from '@/data/piacenza-manifest.json';
const base={provider:'Regione Emilia-Romagna',coverage:'Piacenza and surroundings; individual layers may have partial coverage',resolution:'Original source scale; no accuracy inferred from screen zoom',temporal:'Source edition / feature date; retrieval is not a new observation',frequency:'Provider revisions; locally imported snapshots require re-ingestion',authentication:'None',rateLimits:'Bounded downloads and viewport WMS only; inspection cached for 24 hours',licence:'CC BY 4.0',attribution:'Regione Emilia-Romagna; source feature IDs and links retained',commercial:'Permitted with attribution',redistribution:'Permitted with attribution; original fields retained',lastSync:manifest.retrievedAt,authority:'A' as const,version:'Snapshot / services reviewed 2026-09-30',publication:'See source metadata',status:'enabled' as const};
export const piacenzaSources:Source[]=[
 ...regionalLayers.map(l=>({...base,id:l.id,name:l.name,description:l.note,access:l.queryable?'WMS display and cached GetFeatureInfo':'WMS display only; no numerical measurement inferred',url:l.licenceUrl,licenceUrl:l.licenceUrl})),
 {...base,id:'rer-geosites',name:'Piacenza geosites & geological itineraries',description:'38 regional geosite records including 4 historical mining geosites. Original point and boundary geometries retained; no entrance coordinates inferred.',access:'WFS 2.0 GEOJSON snapshot; downloadable GeoJSON',url:'https://geo.regione.emilia-romagna.it/schede/geositi/index_prov.jsp',licenceUrl:'https://geoportale.regione.emilia-romagna.it/servizi/servizi-ogc/elenco-capabilities-dei-servizi-wms/informazioni-geoscientifiche/patrimonio-geologico/service-2'},
 {...base,id:'rer-geology',name:'Regional resources, prospecting & outcrop points',description:'Original 10k/50k point features within the Piacenza study rectangle. Nearby provinces are included. Source active/inactive classifications are historical survey attributes.',access:'WFS 2.0 GEOJSON snapshot',resolution:'1:10,000; CARG acquired at 1:25,000',url:'https://geoportale.regione.emilia-romagna.it/catalogo/dati-cartografici/informazioni-geoscientifiche/geologia/carta-geologica-1-25.000/layer-26',licenceUrl:'https://geoportale.regione.emilia-romagna.it/servizi/servizi-ogc/elenco-capabilities-dei-servizi-wms/informazioni-geoscientifiche/geologia/service'},
 {...base,id:'rer-reer',name:'REER hiking trails & exploration POIs',description:'Recorded trails, parking, viewpoints, springs, museums, shelters and cultural POIs. Original dates, difficulty and GPX links retained. Parking access, water potability and trail passability are not guaranteed.',access:'WFS 2.0 GEOJSON snapshot',url:'https://geoportale.regione.emilia-romagna.it/servizi/servizi-ogc/wfs/service-2',licenceUrl:'https://geoportale.regione.emilia-romagna.it/servizi/servizi-ogc/wfs/service-2'},
 {...base,id:'ispra-mines',provider:'ISPRA / APAT',name:'Piacenza historical mining census',description:'36 original Piacenza mining records. Includes non-metallic materials and source productive/inactive/abandoned codes. Census updated to 2006; these are not verified current operating mines or entrances.',coverage:'Piacenza province (source Provincia attribute)',temporal:'Mining from 1870; census updated to 2006',resolution:'Historical point geometry; positional accuracy unspecified',access:'ArcGIS REST, bounded province query; GeoJSON snapshot',licence:'CC BY 4.0 under ISPRA default data policy; service states no specific override',attribution:'ISPRA / APAT, censimento dei siti minerari dismessi',url:'https://sgi2.isprambiente.it/arcgis/rest/services/servizi/siti_dismessi/MapServer/0',licenceUrl:'https://www.isprambiente.gov.it/it/note-legali'},
 {...base,id:'piacenza-piae',provider:'Provincia di Piacenza',name:'PIAE extraction and restoration plans',description:'Linked official PIAE publications: P4, P7, QC1, QC5. Planning areas are not operating-mine evidence. No geometries imported.',access:'Official document links in Piacenza Guides',licence:'Document-specific reuse not verified; linked only',commercial:'No republication',redistribution:'No republication',lastSync:null,status:'reference',url:'https://www.provincia.pc.it/pagina.php?IDpag=317&idbox=58&idvocebox=341',licenceUrl:'https://www.provincia.pc.it/pagina.php?IDpag=317&idbox=58&idvocebox=341'},
 {...base,id:'piacenziano-guides',provider:'Parchi del Ducato',name:'Piacenziano geological walking guides',description:'Linked official park itineraries for Arda, Monte Giogo, Monte La Ciocca, Rio Carbonaro and Rio Stramonte. No invented trail geometry.',access:'Official guide links in Piacenza Guides',licence:'Guide-specific reuse not verified; linked only',commercial:'No republication',redistribution:'No republication',lastSync:null,status:'reference',url:'https://www.parchidelducato.it/parco.stirone.piacenziano/Eitinerari-parco.php',licenceUrl:'https://www.parchidelducato.it/parco.stirone.piacenziano/Eitinerari-parco.php'}
];
