export const PIACENZA_BOUNDS:[number,number,number,number]=[9.15,44.45,10.15,45.2];
const geo='https://geoportale.regione.emilia-romagna.it';
export type RegionalLayer={id:string;name:string;it:string;service:string;layers:string;note:string;licenceUrl:string;queryable:boolean;defaultOn?:boolean};
export const regionalLayers:RegionalLayer[]=[
{id:'rer-bedrock',name:'Detailed geology · 1:10,000',it:'Geologia di dettaglio · 1:10.000',service:'geologia10k',layers:'Unita_geol_10k,Frane_depositi_versante_10k',note:'Regional bedrock and slope deposits. Survey scale varies in the plains.',licenceUrl:geo+'/servizi/servizi-ogc/elenco-capabilities-dei-servizi-wms/informazioni-geoscientifiche/geologia/service',queryable:true,defaultOn:true},
{id:'rer-structures',name:'Faults & geological structures',it:'Faglie e strutture geologiche',service:'geologia10k',layers:'Elementi_strutturali_10k,Limiti_unita_geol_10k',note:'Mapped structural features and geological contacts.',licenceUrl:geo+'/servizi/servizi-ogc/elenco-capabilities-dei-servizi-wms/informazioni-geoscientifiche/geologia/service',queryable:true},
{id:'rer-outcrops',name:'Outcrops & observations',it:'Affioramenti e osservazioni',service:'geologia10k',layers:'Affioramenti_aree_10k,Affioramenti_punti_10k,Punti_osservaz_misura_10k',note:'Original geological field observations.',licenceUrl:geo+'/servizi/servizi-ogc/elenco-capabilities-dei-servizi-wms/informazioni-geoscientifiche/geologia/service',queryable:true},
{id:'rer-caves',name:'Natural caves',it:'Cavità naturali',service:'grotte',layers:'Ingressi_grotte',note:'Recorded cave entrances, not a statement of public access.',licenceUrl:geo+'/servizi/servizi-ogc/elenco-capabilities-dei-servizi-wms/informazioni-geoscientifiche/patrimonio-geologico/service',queryable:true},
{id:'rer-boreholes',name:'Geotechnical investigations',it:'Prove geognostiche',service:'geognostica',layers:'Prove_puntuali_dettaglio',note:'Investigation records, primarily in the plains.',licenceUrl:geo+'/catalogo/dati-cartografici/informazioni-geoscientifiche/geologia/banca-dati-geognostica/layer-1',queryable:true},
{id:'rer-protected',name:'Protected areas & Natura 2000',it:'Aree protette e Natura 2000',service:'areeprotette_natura2000',layers:'Parchi_Riserve_limiti,SIC_ZPS_regionali',note:'Consult the managing authority for applicable rules.',licenceUrl:geo+'/servizi/servizi-ogc/elenco-capabilities-dei-servizi-wms/ambiente/service',queryable:true},
{id:'rer-vegetation',name:'Vegetation · Monte Nero / Stirone',it:'Vegetazione · Monte Nero / Stirone',service:'carta_della_vegetazione',layers:'Monte_Nero_PC,Parco_Stirone',note:'Partial coverage: Monte Nero 2004 and Stirone 2002. Not current canopy density.',licenceUrl:geo+'/servizi/servizi-ogc/elenco-capabilities-dei-servizi-wms/ambiente/service-2',queryable:true},
{id:'rer-dtm',name:'Terrain model · 5 m grid',it:'Modello del terreno · griglia 5 m',service:'dtm5x5_anni70_90',layers:'Dtm5x5_anni70_90',note:'Display of terrain model derived from 1970s–1990s mapping. Not recent LiDAR; no point elevation query.',licenceUrl:geo+'/catalogo/dati-cartografici/altimetria/layer-5',queryable:false},
{id:'rer-history',name:'Historical map · 1853',it:'Carta storica · 1853',service:'carta_storica_regionale_1853',layers:'carta_storica_regionale_1853',note:'Historical cartography, not present-day paths or access.',licenceUrl:geo+'/catalogo/dati-cartografici/cartografia-di-base/cartografia-storica/layer-1',queryable:false},
];
export const localCategories=[['mine','Historical mines','Miniere storiche'],['geosite','Geosites','Geositi'],['resource','Resources & prospecting','Risorse e prospezioni'],['outcrop','Outcrop points','Affioramenti puntuali'],['parking','Recorded parking','Parcheggi censiti'],['spring','Springs & fountains','Sorgenti e fontane'],['viewpoint','Viewpoints','Punti panoramici'],['museum','Museums','Musei'],['heritage','Cultural & landscape POIs','POI culturali e paesaggistici'],['shelter','Shelters & bivouacs','Rifugi e bivacchi'],['visitor','Visitor centres','Centri visita']] as const;
export const regionalReferences=[
{name:'PIAE · Piacenza extraction plans',it:'PIAE · Attività estrattive di Piacenza',url:'https://www.provincia.pc.it/pagina.php?IDpag=317&idbox=58&idvocebox=341',note:'Official P4, P7, QC1 and QC5 maps: extraction areas, resources and quarry restoration. Linked documents; no unverified polygons imported.'},
{name:'Piacenziano · geological walks',it:'Piacenziano · itinerari geologici',url:'https://www.parchidelducato.it/parco.stirone.piacenziano/Eitinerari-parco.php',note:'Park-authority itineraries: Arda, Monte Giogo, Monte La Ciocca, Rio Carbonaro and Rio Stramonte. Refer to the authority for current trail conditions.'},
{name:'Piacenza · regional geosite catalogue',it:'Piacenza · catasto regionale dei geositi',url:'https://geo.regione.emilia-romagna.it/schede/geositi/index_prov.jsp',note:'Original descriptions, scientific interests and bibliographic references.'},
];
export function wmsTile(layer:RegionalLayer){return `https://servizigis.regione.emilia-romagna.it/wms/${layer.service}?service=WMS&version=1.1.1&request=GetMap&layers=${layer.layers}&styles=&format=image/png&transparent=true&srs=EPSG:3857&bbox={bbox-epsg-3857}&width=256&height=256`;}
export function validRegionalPoint(lat:number,lng:number){return Number.isFinite(lat)&&Number.isFinite(lng)&&lng>=PIACENZA_BOUNDS[0]&&lng<=PIACENZA_BOUNDS[2]&&lat>=PIACENZA_BOUNDS[1]&&lat<=PIACENZA_BOUNDS[3];}
